name: PUSH

on:
  push:
  pull_request:
  schedule:
    - cron:  '00 12 * * *'

jobs:
  test-client-kodi:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    name: OS-${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8.2
        architecture: x64
    - run: pip install tox
    - run: tox -c client-kodi/script.module.mock.xbmc
    - run: tox -c client-kodi/script.module.cinema.home.youtube.dl
    - run: tox -c client-kodi/script.module.cinema.home.gui
    - run: tox -c client-kodi/script.cinema.home
